image:
  - Ubuntu
platform:
  - Any CPU
skip_branch_with_pr: true
configuration:
  - Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
    - dotnet tool install Paket --tool-path .paket
    - .paket/paket restore
    - dotnet msbuild -p:Configuration=Release src/Aardvark.sln
    - VERSION=`git describe --abbrev=0` && .paket/paket pack --build-config Release --version $VERSION bin/
