internal readonly record struct PatternRule(string File, string Pattern, string Reason);

internal readonly record struct SourceAnchorRule(string File, string Snippet);

internal sealed class DocsRules
{
    public required IReadOnlyList<string> RequiredFiles { get; init; }
    public required IReadOnlyList<PatternRule> ForbiddenPatterns { get; init; }
    public required IReadOnlyList<PatternRule> RequiredPatterns { get; init; }
    public required IReadOnlyList<SourceAnchorRule> SourceAnchors { get; init; }
    public required IReadOnlySet<string> LinkValidationIgnoreFiles { get; init; }
    public required IReadOnlyList<string> MojibakeTokens { get; init; }

    public static DocsRules CreateDefault()
        => new()
        {
            RequiredFiles =
            [
                "AGENTS.md",
                "ai/README.md",
                "ai/SYMBOL_INDEX.md",
                "ai/SEMANTICS_LINEAR_ALGEBRA.md",
                "ai/SEMANTICS_GEOMETRY_CORE.md",
                "ai/PRIMITIVE_TYPES.md",
                "ai/UTILITIES.md",
                "ai/COLLECTIONS.md",
                "ai/ALGORITHMS.md",
                "ai/PIXIMAGE.md",
                "ai/TENSORS.md",
                "ai/FSHARP_INTEROP.md",
                "ai/INCREMENTAL.md",
                "ai/SERIALIZATION.md",
                "docs/CONTRIBUTING.md",
            ],
            ForbiddenPatterns =
            [
                new("docs/CONTRIBUTING.md", "--config", "build.sh/build.cmd do not support --config."),
                new("docs/CONTRIBUTING.md", "./build.sh --project", "build.sh/build.cmd do not support --project."),
                new("docs/CONTRIBUTING.md", ".\\build.cmd --project", "build.sh/build.cmd do not support --project."),
                new("docs/CONTRIBUTING.md", "./test.sh --filter", "Use dotnet test ... --filter for filtered runs."),
                new("docs/CONTRIBUTING.md", ".\\test.cmd --filter", "Use dotnet test ... --filter for filtered runs."),
                new("AGENTS.md", "F# Projects Reference C#, Never the Reverse", "Repository intentionally has mixed C#/F# reference directions."),
                new("README.md", "ray.Intersects(box", "Ray-box intersection is an extension on the box: box.Intersects(ray, out t)."),
                new("ai/PRIMITIVE_TYPES.md", "ray.Hits(box", "Ray3d has no Hits overload for boxes; use box.Intersects(ray, out t)."),
                new("ai/PRIMITIVE_TYPES.md", "V3d.Dot(", "Dot/Cross/Distance are Vec extension methods, not static V3d members."),
                new("ai/SERIALIZATION.md", "coder.CodeInt32", "Primitive coder methods use C# keyword names: CodeInt, not CodeInt32."),
                new("ai/SERIALIZATION.md", "coder.CodeInt64", "Primitive coder methods use C# keyword names: CodeLong, not CodeInt64."),
                new("ai/FSHARP_INTEROP.md", "getColors", "ColorBrewer has no getColors; use Scheme.getPalette and ColorBrewerSchemes."),
                new("ai/FSHARP_INTEROP.md", "= MicroTime.Now", "MicroTime has no Now member; construct from units or ticks."),
                new("ai/FSHARP_INTEROP.md", "Mem.mebibytes", "Actual API is Mem.ofMebibytes / Mem.FromMebibytes."),
                new("ai/UTILITIES.md", "Telemetry.Reset()", "Actual API is Telemetry.ResetTelemetrySystem()."),
                new("ai/UTILITIES.md", "Constant<float>.Pi", "Pi/E are on Constant / ConstantF, not Constant<T>."),
                new("ai/UTILITIES.md", "Constant<double>.Pi", "Pi/E are on Constant / ConstantF, not Constant<T>."),
                new("ai/PIXIMAGE.md", "PixImage.Load<byte>", "Static generic PixImage.Load<T> is not available."),
                new("ai/PIXIMAGE.md", "PixImage.Load<float>", "Static generic PixImage.Load<T> is not available."),
                new("ai/COLLECTIONS.md", "TryRemove(item)", "ConcurrentHashSet<T> uses Remove, not TryRemove."),
                new("ai/TENSORS.md", "class Matrix<", "Generated tensor containers are structs."),
                new("ai/TENSORS.md", "class Volume<", "Generated tensor containers are structs."),
            ],
            RequiredPatterns =
            [
                new("AGENTS.md", "check-docs.sh", "AGENTS should expose docs checker command."),
                new("AGENTS.md", "check-docs.cmd", "AGENTS should expose docs checker command."),
                new("ai/README.md", "SYMBOL_INDEX.md", "README should expose symbol index."),
                new("ai/README.md", "SEMANTICS_LINEAR_ALGEBRA.md", "README should expose semantic deep-dive docs."),
                new("ai/README.md", "SEMANTICS_GEOMETRY_CORE.md", "README should expose semantic deep-dive docs."),
                new("ai/SEMANTICS_LINEAR_ALGEBRA.md", "row-major", "Linear algebra semantics should state row-major storage."),
                new("ai/SEMANTICS_LINEAR_ALGEBRA.md", "FromCols", "Linear algebra semantics should include conversion guidance."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "TransformPos", "Geometry semantics should explicitly reference TransformPos/TransformDir."),
                new("ai/PIXIMAGE.md", "No static `PixImage.Load<T>(...)` API exists.", "PixImage docs should guard against stale generic load examples."),
                new("ai/UTILITIES.md", "ResetTelemetrySystem", "Utilities docs should use correct telemetry reset API."),
                new("ai/UTILITIES.md", "`FillUniformFull` produce 53-bit samples", "Utilities docs should describe full-precision bulk random generation."),
                new("ai/UTILITIES.md", "`Prime.IsTrueFor(long)` has the same mathematical semantics", "Utilities docs should describe primality and indexed prime-table semantics."),
                new("ai/UTILITIES.md", "already-cached lookups remain lock-free", "Utilities docs should describe cached prime lookup behavior."),
                new("ai/UTILITIES.md", "`PerlinNoise.InterpolateNoise` supports signed coordinates", "Utilities docs should describe signed-domain Perlin interpolation."),
                new("ai/UTILITIES.md", "`LonLatHeightFromXyz` returns longitude in `[-180, 180]` degrees", "Utilities docs should define geocentric inverse units and longitude range."),
                new("ai/UTILITIES.md", "`GaussKruegerEllipsoidToPlane` returns `V3d(easting, northing - 5_000_000, height)`", "Utilities docs should define Gauss-Krueger ordering and northing shift."),
                new("ai/PRIMITIVE_TYPES.md", "`Aardvark.Base.Half` follows `System.Half` comparison conventions", "Primitive type docs should define Half comparison semantics."),
                new("ai/PRIMITIVE_TYPES.md", "`GetHashCode` canonicalizes both groups", "Primitive type docs should define Half collection semantics."),
                new("ai/PRIMITIVE_TYPES.md", "Finite comparison operators are mathematically exact", "Primitive type docs should define exact Fraction comparison semantics."),
                new("ai/PRIMITIVE_TYPES.md", "`IsNaN` and `IsInfinity` are mutually exclusive", "Primitive type docs should define Fraction special-value classification."),
                new("ai/SYMBOL_INDEX.md", "`Fraction` exact comparison and special-value semantics", "The symbol index should expose Fraction semantics."),
                new("ai/TENSORS.md", "`struct` types", "Tensor docs should call out struct container reality."),
                new("docs/CONTRIBUTING.md", "dotnet test src/Aardvark.sln --filter", "Contributing guide should show valid filtered test command."),
                new("AGENTS.md", "mixed C#/F# project references", "Agent guide must reflect actual dependency reality."),
                new("ai/SERIALIZATION.md", "void CodeInt(ref int value);", "Serialization docs should list actual primitive coder names."),
                new("ai/SERIALIZATION.md", "`NetworkOrderBinaryReader` and `NetworkOrderBinaryWriter`", "Serialization docs should define network-order primitive stream semantics."),
                new("ai/SERIALIZATION.md", "these numeric scalar and aggregate operations are allocation-free", "Serialization docs should record network-order allocation behavior."),
                new("ai/INCREMENTAL.md", "CSharp.Data.Adaptive", "C# adaptive examples require the CSharp.Data.Adaptive namespace/package."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "`Box2f`/`Box2d` plane intersections", "Geometry semantics should cover closed, scale-invariant box/plane intersections."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "FastRay", "Geometry semantics should cover FastRay slab-test conventions."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "`Circle3f` and `Circle3d` represent a circle", "Geometry semantics should define Circle3 frame and bound conventions."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "`Radius * sqrt(max(0, 1 - n[i] * n[i]))`", "Geometry semantics should state exact Circle3 projection extents."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "`Ray3f.HitsCylinder` and `Ray3d.HitsCylinder` intersect the finite capped surface", "Geometry semantics should define finite capped-cylinder intersections."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "supplied interval is half-open: `t` must be finite and in `[tmin, tmax)`", "Geometry semantics should define capped-cylinder range boundaries."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "leave the entire hit unchanged", "Geometry semantics should define capped-cylinder accumulator behavior."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "`GeometryFun.Simplify` implements Ramer-Douglas-Peucker", "Geometry semantics should cover polyline simplification."),
                new("ai/SEMANTICS_GEOMETRY_CORE.md", "A distance equal to `epsilon` is within tolerance", "Polyline simplification docs should define threshold inclusion."),
                new("ai/ALGORITHMS.md", "`RealRoots` and `RealRootsNormed` return only finite real roots", "Algorithm docs should define cubic finite-root and NaN-slot semantics."),
                new("ai/ALGORITHMS.md", "`Fun.Variance` and `Fun.StandardDeviation` enumerate", "Algorithm docs should describe one-pass enumerable variance semantics."),
                new("ai/ALGORITHMS.md", "selector exactly once per element", "Algorithm docs should define variance selector invocation semantics."),
                new("ai/SYMBOL_INDEX.md", "`Fun.Variance`, `Fun.StandardDeviation`", "The symbol index should expose enumerable population statistics."),
                new("ai/ALGORITHMS.md", "`MedianWindow` retains the latest values", "Algorithm docs should describe rolling median semantics."),
                new("ai/ALGORITHMS.md", "`MinimumSpanningTree.Create<TVertex, TWeight>(edges)` consumes", "Algorithm docs should define generic minimum-spanning-tree semantics."),
                new("ai/ALGORITHMS.md", "`O(E log E)` time and `O(V + E)` auxiliary memory", "Algorithm docs should state generic minimum-spanning-tree complexity."),
                new("ai/ALGORITHMS.md", "`AdaBoost.Train<T>` treats `iterations` as a strict upper bound", "Algorithm docs should define AdaBoost iteration-budget semantics."),
                new("ai/ALGORITHMS.md", "An all-wrong learner is a perfect inverse", "Algorithm docs should define AdaBoost degenerate-learner semantics."),
                new("ai/ALGORITHMS.md", "`O(K)` time and allocates no managed memory per call", "Algorithm docs should state AdaBoost inference complexity and allocation behavior."),
            ],
            SourceAnchors =
            [
                new("src/Aardvark.Base/Math/Trafos/Matrix_auto.cs", "public partial struct M44d"),
                new("src/Aardvark.Base/Math/Trafos/Matrix_auto.cs", "public static M44d FromCols(V4d col0, V4d col1, V4d col2, V4d col3)"),
                new("src/Aardvark.Base/Math/Trafos/Matrix_auto.cs", "public static V4d operator *(M44d m, V4d v)"),
                new("src/Aardvark.Base/Math/Trafos/Matrix_auto.cs", "public static V3d TransformPos(this M44d m, V3d p)"),
                new("src/Aardvark.Base/Math/Trafos/Matrix_auto.cs", "public static V3d TransposedTransformPos(this M44d m, V3d p)"),
                new("src/Aardvark.Base/Math/Trafos/Trafo_auto.cs", "public readonly partial struct Trafo3d : IEquatable<Trafo3d>"),
                new("src/Aardvark.Base/Math/Trafos/Trafo_auto.cs", "public static Trafo3d operator *(Trafo3d t0, Trafo3d t1)"),
                new("src/Aardvark.Base/Math/Colors/Color.cs", "public readonly struct PixFormat : IEquatable<PixFormat>"),
                new("src/Aardvark.Base.Tensors.CSharp/Tensor_auto.cs", "public partial struct Matrix<Td> : IValidity, IMatrix<Td>, IArrayMatrix"),
                new("src/Aardvark.Base.Tensors.CSharp/Tensor_auto.cs", "public partial struct Volume<Td> : IValidity, IVolume<Td>, IArrayVolume"),
                new("src/Aardvark.Base.Tensors.CSharp/Tensor_auto.cs", "public partial struct Tensor4<Td> : IValidity, ITensor4<Td>, IArrayTensor4"),
                new("src/Aardvark.Base.Tensors.CSharp/PixImage/PixImage.cs", "public static PixImage Load(string filename, IPixLoader loader = null)"),
                new("src/Aardvark.Base.Tensors.CSharp/PixImage/PixImage.cs", "public void SaveAsJpeg(string filename, int quality = PixJpegSaveParams.DefaultQuality,"),
                new("src/Aardvark.Base.Tensors.CSharp/PixImage/PixImage.cs", "public static PixImageInfo GetInfoFromFile(string filename, IPixLoader loader = null)"),
                new("src/Aardvark.Base.Tensors.CSharp/Tensors/ImageTensors.cs", "public static bool HasImageLayout<T>(this Volume<T> volume)"),
                new("src/Aardvark.Base.Telemetry/IProbe.cs", "public static void ResetTelemetrySystem()"),
                new("src/Aardvark.Base/Reporting/Report.cs", "public static void Trace([Localizable(true)] string line, params object[] args)"),
                new("src/Aardvark.Base/Random/IRandomUniform.cs", "private static double ReconstructUniformDoubleFull(IRandomUniform rnd)"),
                new("src/Aardvark.Base/Random/Prime.cs", "public static bool IsTrueFor(long value) => Fun.IsPrime(value);"),
                new("src/Aardvark.Base/Random/Prime.cs", "Volatile.Write(ref primeCount, count);"),
                new("src/Aardvark.Base/Random/PerlinNoise.cs", "private static int FloorToInt(float value)"),
                new("src/Aardvark.Base/Random/PerlinNoise.cs", "public float InterpolateNoise(float x, float y, float z)"),
                new("src/Aardvark.Base/Random/RandomSample.cs", "public static V3d Lambertian(V3d normal, IRandomSeries rnds, int seriesIndex)"),
                new("src/Aardvark.Base/Random/HaltonRandomSeries.cs", "public class HaltonRandomSeries : IRandomSeries"),
                new("src/Aardvark.Base/Geodesy/GeoConversion.cs", "public static V3d XyzFromLonLatHeight(V3d lonLatHeight, GeoEllipsoid ellipsoid)"),
                new("src/Aardvark.Base/Geodesy/GeoConversion.cs", "public static V3d LonLatHeightFromXyz(V3d xyz, GeoEllipsoid ellipsoid)"),
                new("src/Aardvark.Base/Geodesy/GeoConversion.cs", "double longitude = Conversion.DegreesFromRadians(Atan2(xyz.Y, xyz.X));"),
                new("src/Aardvark.Base/Geodesy/GeoConversion.cs", "public static V3d GaussKruegerEllipsoidToPlane("),
                new("src/Aardvark.Base/Geodesy/GeoConversion.cs", "public static V3d GaussKruegerPlaneToEllipsoid("),
                new("src/Aardvark.Base/Geodesy/GeoConsts.cs", "public static readonly GeoEllipsoid Wgs84 = FromAF(6378137.0, 1.0 / 298.257223563);"),
                new("src/Aardvark.Base/Symbol/Symbol.cs", "public readonly struct Symbol : IEquatable<Symbol>, IComparable<Symbol>, IComparable"),
                new("src/Aardvark.Base/AlgoDat/LruCache.cs", "public class LruCache<TKey, TValue>"),
                new("src/Aardvark.Base/AlgoDat/ConcurrentHashSet.cs", "public bool Remove(T item) => m_entries.TryRemove(item, out int dummy);"),
                new("src/Aardvark.Base/AlgoDat/ShortestPath.cs", "public class ShortestPath<T> : IShortestPath<T>"),
                new("src/Aardvark.Base/AlgoDat/MinimumSpanningTree.cs", "public static class MinimumSpanningTree"),
                new("src/Aardvark.Base/AlgoDat/MinimumSpanningTree.cs", "The graph is disconnected and cannot produce a spanning tree."),
                new("src/Aardvark.Base/AlgoDat/AdaBoost.cs", "public static class AdaBoost"),
                new("src/Aardvark.Base/AlgoDat/AdaBoost.cs", "weakClassifiers.Add(new WeakClassifier<T>(-1.0, classifier));"),
                new("src/Aardvark.Base/AlgoDat/AdaBoost.cs", "for (int i = 0; i < m_weakClassifiers.Length; i++)"),
                new("src/Aardvark.Base/Geometry/BbTree.cs", "public class BbTree"),
                new("src/Aardvark.Base/Geometry/Algorithms_auto.cs", "public static int[] Simplify(this V2d[] polyline, double epsilon)"),
                new("src/Aardvark.Base/Geometry/Algorithms_auto.cs", "segments = ArrayPool<long>.Shared.Rent(count);"),
                new("src/Aardvark.Base/Math/Base/DistributionFunction.cs", "public class DistributionFunction"),
                new("src/Aardvark.Base/Math/Base/Half.cs", "private static int SignedMagnitudeOrder(ushort bits)"),
                new("src/Aardvark.Base/Math/Base/Half.cs", "public static Half Max(Half value1, Half value2)"),
                new("src/Aardvark.Base/Math/Base/Fraction.cs", "public struct Fraction : IEquatable<Fraction>"),
                new("src/Aardvark.Base/Math/Base/Fraction.cs", "private static int ComparePositive(ulong aNumerator, ulong aDenominator, ulong bNumerator, ulong bDenominator)"),
                new("src/Aardvark.Base/Math/Base/Fraction.cs", "return IsInfinity(a) ? CanonicalInfinity(a) : CanonicalInfinity(b);"),
                new("src/Aardvark.Base/Math/Base/Fraction.cs", "return f.Denominator == 0 && f.Numerator == 0;"),
                new("src/Aardvark.Base/Math/Base/Fun_auto.cs", "private static double FinalizeVariance(long count, KahanSum deviationSum, KahanSum squaredDeviationSum)"),
                new("src/Aardvark.Base/Math/Base/Fun_auto.cs", "double deviation = VarianceDifference(x, origin);"),
                new("src/Aardvark.Base/Math/Base/MedianWindow.cs", "public class MedianWindow"),
                new("src/Aardvark.Base/Math/Numerics/Polynomial.cs", "public static class Polynomial"),
                new("src/Aardvark.Base/Math/Numerics/Polynomial.cs", "return (root, double.NaN, double.NaN);"),
                new("src/Aardvark.Base/Math/Numerics/Polynomial.cs", "if (!added) q.Set(i++, d + shift);"),
                new("src/Aardvark.Base/Math/Numerics/Polynomial.cs", "private static double RefineCubicDiscriminant("),
                new("src/Aardvark.Base.IO/ICoder_auto.cs", "void CodeInt(ref int value);"),
                new("src/Aardvark.Base.IO/NetworkOrderBinaryReader.cs", "return Fun.FloatFromBits(BinaryPrimitives.ReverseEndianness(base.ReadInt64()));"),
                new("src/Aardvark.Base.IO/NetworkOrderBinaryWriter.cs", "base.Write(BinaryPrimitives.ReverseEndianness(Fun.FloatToBits(value)));"),
                new("src/Aardvark.Base/Geometry/IntersectionTests_auto.cs", "double min = nx * (nx < 0 ? xmax : xmin) + ny * (ny < 0 ? ymax : ymin);"),
                new("src/Aardvark.Base/Geometry/Types/Ray/Ray3_auto.cs", "public readonly struct FastRay3d"),
                new("src/Aardvark.Base/Geometry/Types/Ray/Ray3_auto.cs", "private readonly bool TryGetCylinderHit("),
                new("src/Aardvark.Base.FSharp/Datastructures/Geometry/Boundable.fs", "if ray.HitsCylinder(cylinder.P0, cylinder.P1, cylinder.Radius, x.TMin, x.TMax, &t) then"),
                new("src/Aardvark.Base/Geometry/Types/Circle/Circle3_auto.cs", "private readonly V3d UnitTangent"),
                new("src/Aardvark.Base/Geometry/Types/Circle/Circle3_auto.cs", "Radius * Fun.Sqrt(Fun.Max(0, 1 - Normal.X * Normal.X))"),
                new("src/Aardvark.Base/Geometry/SpecialPoints_auto.cs", "public static double GetMinimalDistanceTo(this V3d point, Ray3d ray, out double t)"),
                new("src/Aardvark.Base/Geometry/SpecialPoints_auto.cs", "public static double GetMinimalDistanceTo(this Ray3d ray0, Ray3d ray1, out double t0, out double t1)"),
                new("src/Aardvark.Base.FSharp/Utilities/Interop/HashSet.fs", "let inline unionWith (xs : seq<'a>) (s : HashSet<'a>) ="),
            ],
            LinkValidationIgnoreFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase),
            MojibakeTokens = ["â", "Ã", "Â", "�"],
        };
}
