// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load @"load-references.fsx"
#load @"..\Core\PriorityQueue.fs"
      @"..\Core\WeakSet.fs"
      @"..\Core\Delta.fs"
      @"..\Core\ReferenceCountingSet.fs"
      @"..\Core\TimeList.fs"
      @"..\Core\Cache.fs"
      @"..\Core\Core.fs"
      @"..\Mod\Mod.fs"
      @"..\AdaptiveSet\AdaptiveSetCore.fs"
      @"..\AdaptiveSet\ChangeableSet.fs"
      @"..\AdaptiveSet\AdaptiveSet.fs"
      @"..\AdaptiveList\AdaptiveListCore.fs"
      @"..\AdaptiveList\ChangeableList.fs"
      @"..\AdaptiveList\AdaptiveList.fs"
      @"..\Builders.fs"
      @"..\CSharp.fs"
      @"..\Adapters\EventAdapter.fs"
      @"..\Tests\AdaptiveSetReference.fs"
      @"..\Tests\ASetUtilities.fs"
      @"..\Tests\ModTests.fs"
      @"..\Tests\ASetTests.fs"
      @"..\Tests\AListTests.fs"
