name: Publish
on:
  push:
    branches:
      - master
      - newbuild
    paths:
      - RELEASE_NOTES.md
      - .github/workflows/publish.yml
jobs:
  pack:
    name: Package
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy global.json
        run: cp ./.github/global.json .
      - name: Install Dotnet
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore
        run: dotnet paket restore
      # - name: Generate Code
      #   shell: cmd
      #   run: generate.cmd
      - name: Build
        shell: cmd
        run: dotnet build -c Release src\Aardvark.sln
      - name: Pack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet aardpack src\Aardvark.sln --notag
      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: bin\pack
      - name: GitHub Packages
        env:
          NUGET_KEY: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: dotnet nuget push "bin\pack\*.nupkg" -k %NUGET_KEY% -s "https://nuget.pkg.github.com/aardvark-platform/index.json" --skip-duplicate
      - name: NuGet
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: cmd
        run: dotnet nuget push "bin\pack\*.nupkg" -k %NUGET_KEY% -s "https://api.nuget.org/v3/index.json" --skip-duplicate