name: Windows

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.100'
    - name: build
      run: .\build.cmd
